### PR TITLE
use Conda version of TorchMetrics

### PR DESCRIPTION
**Pull request by Borda**
preferably use Conda version, similar could be done also with PL except Conda does not support extras
- https://anaconda.org/conda-forge/torchmetrics
- https://anaconda.org/conda-forge/pytorch-lightning

### CODE REVIEW

**Comment by krasserm** [comment]
Isn't this obsolete if we include `requirements.txt` into `environment.yml` as proposed [here](https://github.com/krasserm/perceiver-io/pull/5#pullrequestreview-845316985)?

**Comment by Borda** [comment]
> Isn't this obsolete if we include `requirements.txt` into `environment.yml` as proposed [here](https://github.com/krasserm/perceiver-io/pull/5#pullrequestreview-845316985)?

yes and no... :rabbit: if people are using Conda environment, they may find some advantage if they source also Conda version of packages (the binary is mostly the same but Conda used to have better version resolving)

**Comment by krasserm** [comment]
> yes and no... rabbit if people are using Conda environment, they may find some advantage if they source also Conda version of packages (the binary is mostly the same but Conda used to have better version resolving)

I'm more worried about redundancies in dependency specification (across `requirements.txt` and `environment.yml`). If there is no clear advantage of using conda dependency resolution for this particular configuration, I'd prefer having `requirements.txt` included into `environment.yml` via `-r requrirements.txt`.

**Comment by Borda** [comment]
> > yes and no... rabbit if people are using Conda environment, they may find some advantage if they source also Conda version of packages (the binary is mostly the same but Conda used to have better version resolving)
> 
> I'm more worried about redundancies in dependency specification (across `requirements.txt` and `environment.yml`). If there is no clear advantage of using conda dependency resolution for this particular configuration, I'd prefer having `requirements.txt` included into `environment.yml` via `-r requrirements.txt`.

I see and it is good, the only thing I a not sure about is how Conda handle duplicates, cor example if you have pytorch in Conda and are referred again as torch in requirements.txt

as mentioned in https://github.com/krasserm/perceiver-io/pull/5#issuecomment-1006454053 let's do some investigation first, so turn this PR as draft till I know the answer to this limitation

**Comment by krasserm** [comment]
> I see and it is good, the only thing I a not sure about is how Conda handle duplicates, cor example if you have pytorch in Conda and are referred again as torch in requirements.txt

If we follow the rule to add dependencies to `requirements.txt` by default and add dependencies to `environment.yml` only where it is convenient (e.g. for CUDA toolkit), avoiding duplicates shouldn't be really an issue. OTOH, keeping two dependency specs in sync is much harder ...

**Comment by Borda** [comment]
yes, what I am thinking now is we can instead of adding `-r requirements.txt` do something like install self (after merging #5) which shall automatically take package dependencies and install only missing...

**Comment by krasserm** [comment]
Sounds good to me!

**Comment by krasserm** [comment]
@Borda, closing this pull request as install self is now covered by #9, with dependencies specified in [pyproject.toml](https://github.com/krasserm/perceiver-io/blob/main/pyproject.toml). It is based on [this project template](https://github.com/cstub/python-project-template) by @cstub. Thanks again for your PR, it inspired work done in #9.

**Pull request closed without merging**
